### PR TITLE
Fix strange line endings

### PR DESCRIPTION
**Pull request by graingert**
There seems to be some strange line endings that's causing my git
to freak out.

| Q                 | A
| ----------------- | ---
| Bug fix?          | yes/no
| Breaking change?  | yes/no
| New feature?      | yes/no
| Deprecations?     | yes/no
| Spec compliancy?  | yes/no
| Tests added/pass? | yes/no
| Fixed tickets     | comma-separated list of tickets fixed by the PR, if any
| License           | MIT

### CODE REVIEW

**Comment by graingert** [comment]
I'm sure these files are intentional, but my git automatically does CRLF changes on them

**Comment by graingert** [comment]
```
warning: CRLF will be replaced by LF in test/fixtures/core/uncategorised/100/actual.js.
The file will have its original line endings in your working directory.
warning: CRLF will be replaced by LF in test/fixtures/core/uncategorised/437/actual.js.
The file will have its original line endings in your working directory.
warning: CRLF will be replaced by LF in test/fixtures/core/uncategorised/439/actual.js.
The file will have its original line endings in your working directory.
warning: CRLF will be replaced by LF in test/fixtures/core/uncategorised/443/actual.js.
The file will have its original line endings in your working directory.
warning: CRLF will be replaced by LF in test/fixtures/core/uncategorised/50/actual.js.
The file will have its original line endings in your working directory.
warning: CRLF will be replaced by LF in test/fixtures/es2015/uncategorised/22/actual.js.
The file will have its original line endings in your working directory.
warning: CRLF will be replaced by LF in test/fixtures/es2015/uncategorised/23/actual.js.
The file will have its original line endings in your working directory.
warning: CRLF will be replaced by LF in test/fixtures/esprima/expression-primary/literal/string/migrated_0017.js.
The file will have its original line endings in your working directory.
warning: CRLF will be replaced by LF in test/fixtures/esprima/invalid-syntax/migrated_0155/actual.js.
The file will have its original line endings in your working directory.
warning: CRLF will be replaced by LF in test/fixtures/esprima/invalid-syntax/migrated_0159/actual.js.
The file will have its original line endings in your working directory.
```

**Comment by graingert** [comment]
I suspect it would be better to exclude these files in:

`* text eol=lf`

**Comment by danez** [comment]
Thanks

**Pull request merged**
