### PR TITLE
Reuse plugin "extend" function definitions

### PR DESCRIPTION
**Pull request by zertosh**
| Q                 | A
| ----------------- | ---
| Bug fix?          | no
| Breaking change?  | no
| New feature?      | no
| Deprecations?     | no
| Spec compliancy?  | no
| Tests added/pass? | no
| Fixed tickets     | 
| License           | MIT

The functions passed to `instance.extend` do not themselves need to be re-defined every time you create a new instance. I know this PR creates history noisy, so no hard feelings if you don't want to merge it. Also, I'd be more than happy to backport it to 6.x.

To best see the changes, use `?w=1`: https://github.com/babel/babylon/pull/435/files?w=1

### CODE REVIEW

**Comment by danez** [comment]
Do you think this would be better with #393 ?

**Comment by zertosh** [comment]
@danez looks like no. In #393, they're defining new "extension plugin" classes every time you create a new parser instance. Seems like a trade-off between perf and types :/

**Comment by danez** [comment]
I think this might have been fixed now with #459 as the actual class now gets cached. 
Anyway this seems to conflict heavily with the other PR, so we should probably close this, but if you have further ideas how to improve babylon open another PR.
Thanks for looking into this.

**Comment by zertosh** [comment]
Ah the class caching approach is so much better, thanks @danez!

**Pull request closed without merging**
