### PR TITLE
Fix number parser

### PR DESCRIPTION
**Pull request by alxpy**
| Q                 | A
| ----------------- | ---
| Bug fix?          | yes
| Breaking change?  | yes
| New feature?      | no
| Deprecations?     | no
| Spec compliancy?  | yes
| Tests added/pass? | yes
| Fixed tickets     | #420 
| License           | MIT

### CODE REVIEW

**Comment by alxpy** [comment]
fixed
https://github.com/babel/babylon/issues/420#issuecomment-289854552

**Comment by hzoo** [comment]
Hey @alxpy! It looks like one or more of your builds have failed. I've copied the relevant info below to save you some time.

* [Node vlts/* - linux](https://travis-ci.org/babel/babylon/jobs/216471544)
* [Node vlts/* - linux](https://travis-ci.org/babel/babylon/jobs/216471545)

**Comment by alxpy** [comment]
hmm, I can't find [this line](https://travis-ci.org/babel/babylon/jobs/216471545#L1368) in the [project](https://github.com/babel/babylon/search?utf8=%E2%9C%93&q=0274134317073&type=)...

**Comment by existentialism** [comment]
@alxpy it's from [flow's parser tests](https://github.com/facebook/flow/blob/master/src/parser/test/hardcoded_tests.js#L5376), run by [`run_flow_tests`](https://github.com/babel/babylon/blob/master/scripts/run_flow_tests.js).

**Comment by alxpy** [comment]
It looks like this test fails in the master too (I cloned repo in new folder and ran tests on master)... how is it possible?
@existentialism

**Comment by hzoo** [comment]
Hey @alxpy! It looks like one or more of your builds have failed. I've copied the relevant info below to save you some time.

* [Node vlts/* - linux](https://travis-ci.org/babel/babylon/jobs/216528577)
* [Node vlts/* - linux](https://travis-ci.org/babel/babylon/jobs/216528579)

**Comment by bakkot** [comment]
@alxpy CI was broken on master, fixed by #442. If you force-push it should clear it up.

**Comment by alxpy** [comment]
@bakkot thanks!

**Comment by danez** [comment]
Thanks you @alxpy

**Pull request merged**
