### PR TITLE
Allow plugins:["*"]

### PR DESCRIPTION
**Pull request by danez**
| Q                 | A
| ----------------- | ---
| Bug fix?          | no
| Breaking change?  | no
| New feature?      | yes
| Deprecations?     | no
| Spec compliancy?  | no
| Tests added/pass? | no
| Fixed tickets     | no

### CODE REVIEW

**Comment by hzoo** [comment]
A test using `*` would be good 😄

**Comment by hzoo** [comment]
a bug fix since it should of worked before?

**Comment by krainboltgreene** [comment]
Does this mean I can automatically load all plugins I have installed? How does it figure out which package is a plugin?

**Comment by DrewML** [comment]
@krainboltgreene Bablyon doesn't support external plugins (so _plugin_ is a bit of a misnomer here). The `plugins` option takes an array of strings for _built-in_ parser plugins.

**Comment by hzoo** [comment]
Right this is only for the parser plugins https://github.com/babel/babylon#plugins - it's basically a truthy check in the parser to either make it say "unexpected token" or to parse it.

**Pull request merged**
