### PR TITLE
Add support for computed class property names (#120)

### PR DESCRIPTION
**Pull request by motiz88**
First time contributor here - someone please check this for sanity :smile:

I _think_ this implements #120 quite completely. I'm working on a PR for the corresponding changes required in Babel, tracked by babel/babel#4499.

### CODE REVIEW

**Comment by motiz88** [comment]
The CI failures (on Node 5 only, out of the whole build matrix) [appear to be unrelated](https://travis-ci.org/babel/babylon/jobs/159109742#L4348) to the PR's content. (Right?)

**Comment by danez** [comment]
Thanks for contributing.

This looks good, the only thing that I'm worried about this is how the ambiguous cases are handled. For example this class:
```
class Bar {
   [x] = blub
   ['y'];
}
```
Does it contain two or one properties? I would assume one with a value of `blub['y']`. But I'm not sure what the spec says about this if it does.
What would your changes produce for this example?

**Comment by motiz88** [comment]
My immediate answer is that ASI applies like everywhere else (and there are existing tests for literal-named properties reflecting this). Doing a little bit of research and will follow up soon.

**Comment by danez** [comment]
I found this
https://github.com/tc39/proposal-class-public-fields/issues/25

Not sure what the current status is, but semicolons might be required in the case i posted.

**Comment by danharper** [comment]
There's some [existing tests](https://github.com/babel/babylon/tree/master/test/fixtures/experimental/class-properties), which cover the ASI rules in this case for computed methods.

**Comment by danez** [comment]
Good catch.

**Comment by motiz88** [comment]
There's also tc39/proposal-class-public-fields/pull/45 (an open PR at the moment) which suggests the semicolon is not in the spec, but IMHO it's safe to assume it will be (given past discussions and the nontrivial ambiguity otherwise).

**Comment by motiz88** [comment]
@danez your `class Bar` parses as having one property.

**Comment by hzoo** [comment]
Yeah ref https://github.com/babel/babel/pull/3332

**Comment by hzoo** [comment]
Looks fine to me? We made semicolons necessary before but it was reverted

**Comment by jeffmo** [comment]
The tests like right to me

**Comment by danez** [comment]
@jeffmo what will the spec say about this case? Or is it not yet decided?

```
class Bar {
   [x] = foo
   ['y'];
}
```

**Comment by jeffmo** [comment]
@danez: Grammatically, that would be the same as:

```
class Bar {
  [x] = foo['y'];
}
```

This is just the practical fallout of supporting ASI in the language unfortunately.

**Pull request merged**
