### PR TITLE
"yield" parsing inside function name and parameters

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
| Q                 | A
| ----------------- | ---
| Bug fix?          | yes
| Breaking change?  | 
| New feature?      | 
| Deprecations?     |
| Spec compliancy?  | yes
| Tests added/pass? | yes
| Fixed tickets     | 
| License           | MIT

Currently I have only written some tests. Babylon fails to parse the ignored ones, I will fix them in the following commits.
I have create a new folder (`fixtures/es2015/yield`) even if there was already `fixtures/esprima/es2015-yield`, to keep there only the original esprima tests. Some of them are wrong, I will remove them later.
Many of the tests I addedd already works in Babylon, but I added them to prevent possible regressions and to have all the tests about yield in the same place.

<details>
<summary>I think this PR will allow us to remove the following tests from `test262_whitelist.txt`:</summary>

```
language/expressions/arrow-function/param-dflt-yield-expr.js(default)
language/expressions/arrow-function/param-dflt-yield-expr.js(strict mode)
language/expressions/function/param-dflt-yield-strict.js(strict mode)
language/expressions/generators/param-dflt-yield.js(default)
language/expressions/generators/yield-as-generator-expression-binding-identifier.js(default)
language/expressions/generators/yield-as-parameter.js(default)
language/expressions/object/method-definition/generator-param-id-yield.js(default)
language/expressions/object/method-definition/generator-param-init-yield.js(default)
language/expressions/object/method-definition/yield-as-parameter.js(default)
language/statements/function/param-dflt-yield-strict.js(strict mode)
language/statements/generators/param-dflt-yield.js(default)
language/statements/generators/yield-as-parameter.js(default)
language/expressions/arrow-function/syntax/arrowparameters-bindingidentifier-yield.js(default)
language/statements/generators/yield-as-function-expression-binding-identifier.js(default)
language/statements/generators/yield-as-function-expression-binding-identifier.js(default)
```
</details>

TODO:
- [x] Fix the bugs with normal and generator functions.
- [x] Fix the bugs with arrow functions (this is trickier, it requires some backtracking)
- [x] Remove the tests from the whitelist and check the esprima tests
- [x] Make the error messages more consistent. Currently for yield binding in strict mode we have:
  - `Binding yield in strict mode` (`function yield() { "use strict"; }`)
  - `yield is a reserved word` (`"use strict"; function yield() {}`, `"use strict"; let yield;`)
  - `yield is a reserved word in strict mode` (`function fn(yield) { "use strict"; }`)
- [ ] `await` has similar semantics, maybe it has the same bugs?

(Thanks Logan for having helped me on Slack to understand the correct semantics!)

### CODE REVIEW

**Comment by nicolo-ribaudo** [comment]
This PR is ready for review. Some tests are duplicated in `esprima/es2015-yield` and `es2015/yield`. I prefer to have all the tests related to `yield` inside function name/parameters together; if you think that it is better to not have duplicated tests, I can delete them from `es2015/yield`.

**Comment by nicolo-ribaudo** [comment]
Effectively all these commits are quite a mess, sorry 😂
I will reorganize the changes of this PR when I get home, so that it can be reviewed commit-by-commit more easily

**Comment by nicolo-ribaudo** [comment]
@jridgewell I reorganized the commits to make it easier to review them. They do not overlap, so they can effectively be reviewed grouped in chunks (I added some labels that I think represent a good way of suddivising the commits for an easier review: [funct](https://github.com/babel/babylon/pull/689/files/8c77073ac91497bb4c5d7329923d1b29cbefaf67..ad3863c011a50667fd350b7fa9d7bc60218d80fd), [arrow](https://github.com/babel/babylon/pull/689/files/ad3863c011a50667fd350b7fa9d7bc60218d80fd..a00a05b37ec06fd6425b97e5b02c567ce12e2521) and [err msg](https://github.com/babel/babylon/pull/689/files/a00a05b37ec06fd6425b97e5b02c567ce12e2521..2738bd4218406a4f488591ef888f9d948828f237))

**Comment by nicolo-ribaudo** [comment]
@danez Do you want that I rebase this PR?

**Comment by danez** [comment]
That would be nice, can also remove my two merges, somehow github cannot handle this here.

**Pull request closed without merging**
