### PR TITLE
Fixed invalid number literal parsing

### PR DESCRIPTION
**Pull request by alxpy**
| Q                 | A
| ----------------- | ---
| Bug fix?          | yes
| Breaking change?  | no
| New feature?      | no
| Deprecations?     | no
| Spec compliancy?  | yes
| Tests added/pass? | yes
| Fixed tickets     | #467
| License           | MIT

### CODE REVIEW

**Comment by hzoo** [comment]
Hey @alxpy! It looks like one or more of your builds have failed. I've copied the relevant info below to save you some time.

* [Node vlts/* - linux](https://travis-ci.org/babel/babylon/jobs/222600053)
* [Node vlts/* - linux](https://travis-ci.org/babel/babylon/jobs/222600054)

**Comment by alxpy** [comment]
Is `test-babel` failed in `master`?

**Comment by danez** [comment]
It seems this breaks parsing of numbers, this test in babel fails on line 2
https://github.com/babel/babel/blob/master/packages/babel-generator/test/fixtures/flow/number-literal-types/actual.js

**Comment by hzoo** [comment]
Hey @danez! It looks like one or more of your builds have failed. I've copied the relevant info below to save you some time.

* [Node v4 - linux](https://travis-ci.org/babel/babylon/jobs/224338930)
* [Node v6 - linux](https://travis-ci.org/babel/babylon/jobs/224338931)
* [Node v7 - linux](https://travis-ci.org/babel/babylon/jobs/224338932)
* [Node vlts/* - linux](https://travis-ci.org/babel/babylon/jobs/224338933)
* [Node vlts/* - linux](https://travis-ci.org/babel/babylon/jobs/224338935)
* [Node vlts/* - linux](https://travis-ci.org/babel/babylon/jobs/224338936)

**Comment by danez** [comment]
Thank you, I fixed the PR by using the same fix that acorn implemented. It is usually always a good check to see if acorn has the same bug as babylon or not.
If not we can probably find the fix there (https://github.com/ternjs/acorn/commit/b14cb8bea7b5fd69fb6dcf2b75cf6fb772e79ed6) (and the codebase is pretty similar as babylon is a fork)
If also acorn has the same problem we could potentially also fix it easily there. (For example this PR https://github.com/ternjs/acorn/pull/540 which you also created here some time ago.)

**Comment by alxpy** [comment]
@danez, thanks for the help! (recently I was very busy)

**Pull request merged**
