### PR TITLE
[WIP] Fixed QualifiedTypeIdentifier

### PR DESCRIPTION
**Pull request by alxpy**
| Q                 | A
| ----------------- | ---
| Bug fix?          | yes
| Breaking change?  | 
| New feature?      | no
| Deprecations?     | no
| Spec compliancy?  | yes
| Tests added/pass? | yes
| Fixed tickets     | #455
| License           | MIT

### CODE REVIEW

**Comment by hzoo** [comment]
Hey @alxpy! It looks like one or more of your builds have failed. I've copied the relevant info below to save you some time.

* [Node v4 - linux](https://travis-ci.org/babel/babylon/jobs/221132358)
* [Node v6 - linux](https://travis-ci.org/babel/babylon/jobs/221132360)
* [Node v7 - linux](https://travis-ci.org/babel/babylon/jobs/221132362)
* [Node vlts/* - linux](https://travis-ci.org/babel/babylon/jobs/221132363)
* [Node vlts/* - linux](https://travis-ci.org/babel/babylon/jobs/221132365)
* [Node vlts/* - linux](https://travis-ci.org/babel/babylon/jobs/221132366)

**Comment by alxpy** [comment]
@thejameskyle what should we get in this case? -- `type b = a.b.c;`
```
- type: QualifiedTypeIdentifier
  id: Identifier(a)
  qualification:
    - type: QualifiedTypeIdentifier
      id: Identifier(b)
      qualification: Identifier(c)
```
it will be right?

**Comment by danez** [comment]
You can check on http://astexplorer.net/, it should match flow.

http://astexplorer.net/#/gist/814a0550f3bc1050df71f6548290cb41/38edaa6b3331f05685dbc44516f827d380a2f87e

**Comment by alxpy** [comment]
so `babylon` works the same as `flow`...
is it realy bug -- https://github.com/babel/babylon/issues/455?

/cc @danez, @thejameskyle

**Comment by danez** [comment]
Yes agree, seems we are doing the same thing as the flow parser, not sure why this should be a bug.

**Pull request closed without merging**
