### PR TITLE
Mention cloning of repository in CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by sumedh123**
| Q                 | A
| ----------------- | ---
| Bug fix?          | yes/no
| Breaking change?  | yes/no
| New feature?      | yes/no
| Deprecations?     | yes/no
| Spec compliancy?  | yes/no
| Tests added/pass? | yes/no
| Fixed tickets     | comma-separated list of tickets fixed by the PR, if any
| License           | MIT

Newbies who see towards contributing.md should get a clear view how to get the project up and running locally. It is actually a small change but I think it should be there.

### CODE REVIEW

**Comment by sumedh123** [comment]
@xtuc  Should I remove '$' or will you take care of that?

**Comment by xtuc** [comment]
Yes, go ahead :+1:

**Comment by hzoo** [comment]
This is for 7.0, so we use yarn for install now, otherwise 👍

**Comment by sumedh123** [comment]
@hzoo  So do we need to update the full document now?

**Comment by hzoo** [comment]
I got it thanks!

**Pull request merged**
