### PR TITLE
Add yield-result

### PR DESCRIPTION
**Pull request by pudility**
| Q                 | A
| ----------------- | ---
| Bug fix?          | no
| Breaking change?  | no
| New feature?      | no
| Deprecations?     | no
| Spec compliancy?  | N/A
| Tests added/pass? | yes
| Fixed tickets     | [#100](https://github.com/babel/babylon/issues/100)
| License           | MIT

I added test cases for yield result and yield result with parenthesis.

### CODE REVIEW

**Comment by nicolo-ribaudo** [comment]
Can you move these tests to the flow/typecast directory?

**Comment by pudility** [comment]
@nicolo-ribaudo is that what you meant?

**Comment by nicolo-ribaudo** [comment]
Yes

**Comment by existentialism** [comment]
@pudility thanks!

**Pull request merged**
