### PR TITLE
Clean up uncategorised tests 

### PR DESCRIPTION
**Pull request by pudility**
| Q                 | A
| ----------------- | ---
| Bug fix?          | no
| Breaking change?  | no
| New feature?      | no
| Deprecations?     | no
| Spec compliancy?  | N/A
| Tests added/pass? | no
| Fixed tickets     | None
| License           | MIT

I moved `babylon/test/fixtures/experimental/uncategorised/1` and `babylon/test/fixtures/experimental/uncategorised/2` into 

~~`babylon/test/fixtures/experimental/parenthesized-expression/parenthesized-braces-expression` and `babylon/test/fixtures/experimental/parenthesized-expression/parenthesized-brackets-expression`~~ 

`babylon/test/fixtures/es2015/destructuring/parenthesized-lhs-object/` and `babylon/test/fixtures/es2015/destructuring/parenthesized-lhs-array/` respectively. In order to organize the test folder.

### CODE REVIEW

**Comment by nicolo-ribaudo** [comment]
Since they are about destructing, can you move them to `es2015/destructing` (e.g. `es2015/destructing/parenthesized-lhs-object`)

**Comment by pudility** [comment]
Absolutely! Just moved them. Thanks for the input.

**Comment by existentialism** [comment]
@pudility slight gotcha, notice the `expected.json` you just added is empty?

The test runner assumes the following sort of folder structure:
`/test/fixtures/{category}/{subject}/{test_name}`

You currently have:
`/test/fixtures/es2015/destructuring/parenthesized-lhs-object/parenthesized-braces-expression`
`/test/fixtures/es2015/destructuring/parenthesized-lhs-object/parenthesized-brackets-expression`

It isn't actually running your nested tests:

image


To get this to work, you'll want to flatten this by a level:
`/test/fixtures/es2015/destructuring/parenthesized-lhs-object/actual.js`
`/test/fixtures/es2015/destructuring/parenthesized-lhs-object/options.json`
`/test/fixtures/es2015/destructuring/parenthesized-lhs-array/actual.js`
`/test/fixtures/es2015/destructuring/parenthesized-lhs-array/options.json`

**Comment by pudility** [comment]
@existentialism So sorry about that, I have updated my PR accordingly.

**Comment by existentialism** [comment]
@pudility no need to apologize, we definitely appreciate you helping us clean this up!

**Pull request merged**
