### PR TITLE
Export plugins

### PR DESCRIPTION
**Pull request by urish**
This will allow users of the module to define third-party plugins

| Q                 | A
| ----------------- | ---
| Bug fix?          | no
| Breaking change?  | no
| New feature?      | yes
| Deprecations?     | no
| Spec compliancy?  | yes
| Tests added/pass? | pass
| Fixed tickets     | #500
| License           | MIT

This will allow users of the module to define third-party plugins:

```javascript
    var babylon = require('babylon')

    babylon.plugins.customPlugin = function(parser) {
         ...
    };
    
    babylon.parse('someExpression()', { plugins: [ 'customPlugin'] });
```

### CODE REVIEW

**Comment by fahad19** [comment]
💖

**Comment by loganfsmyth** [comment]
Duplicate of https://github.com/babel/babylon/pull/11, https://github.com/babel/babel/issues/4245, and https://github.com/babel/babel/issues/1351, among others I'm sure.

The PR isn't just asking to expose some object, it's asking us to maintain a whole official API for parser plugins to use, which isn't something we're willing to commit to currently, as it's not clear how to make that API effective, and it would limit out ability to refactor and optimize the codebase.

We do allow people to fork `babylon` currently, and use `{ parserOpts: {parser: require("custom-parser")}}` in the options if you want to experiment with something as a custom syntax, but that is the limit of it currently.

**Comment by urish** [comment]
Actually, for my purpose - no API for plugins is needed. If you merge it as-is, without any commitment from your side, I will be super-happy

**Comment by loganfsmyth** [comment]
Your example code takes `parser` as an argument. That is an API. We could change the method names on that instance at any time. If we exposed this, we'd break any custom plugins any time we did that.

**Comment by urish** [comment]
True, but I'm (and perhaps other?) happy to live with exported plugins object despite the fact it might even be removed at some point, if you decide to do so.

It is still so much better than [hacks like this](https://github.com/lukehorvat/babby/blob/b925e8151c6d5f58abe893cb9680221416bfaa4b/lib/babylon.js#L6) people are currently doing.

**Comment by loganfsmyth** [comment]
Currently we don't endorse having plugins that affect syntax. 

> It is still so much better than hacks like this people are currently doing.

"better" here is relative though. If we expose `plugins` as a mutable object, it will encourage people to hack them in anyway. The fact that it is a gross pain in the ass right now is a good thing, because it makes it obvious that it isn't something we support people doing.

> I'm happy to live with exported plugins object despite the fact it might even be removed at some point, if you decide to do so.

But you aren't the person people will be yelling at. If you hack something together, publish it, people start using it, and then we break it because we didn't even know about it and it used a hack to add it in there, average users will have no idea, they'll just see that their Babel-based project is now broken, and we'll be the ones stuck in the position of either leaving users broken, or then having to support the hack long-term.

**Comment by urish** [comment]
Got it. So do you currently recommend on forking babylon, making whatever changes and then publishing to NPM so it can be consumed by babel? Or is there a better way to go?

**Comment by hzoo** [comment]
Yeah that's the recommendation: added to the readme now https://github.com/babel/babylon#will-babylon-support-a-plugin-system

Thanks for the PR though.

**Pull request closed without merging**
