### PR TITLE
Add yield result

### PR DESCRIPTION
**Pull request by pudility**
| Q                 | A
| ----------------- | ---
| Bug fix?          | no
| Breaking change?  | no
| New feature?      | no
| Deprecations?     | no
| Spec compliancy?  | N/A
| Tests added/pass? | yes
| Fixed tickets     | [#100](https://github.com/babel/babylon/issues/100)
| License           | MIT

I added test cases for yield result and yield result with parenthesis.

### CODE REVIEW

**Comment by nicolo-ribaudo** [comment]
This PR shouldn't include the commits merged in #731

**Comment by jridgewell** [comment]
Yup, looks like this needs a rebase.

**Comment by pudility** [comment]
Sorry about that, I can fix it later (I am at school the rest of today sorry).

**Comment by pudility** [comment]
I rebased the repo, I am going to close this PR and create a new one. Thanks!

**Comment by existentialism** [comment]
@pudility sounds good, but next time you can always force push to this branch too!

**Comment by pudility** [comment]
@existentialism Thanks for the tip! I will try to use that next time. I am pretty new to git and still learning about all of it's features.

**Pull request closed without merging**
