### PR TITLE
Add more tests for the nullish coalescing operator

### PR DESCRIPTION
**Pull request by azz**
| Q                 | A
| ----------------- | ---
| Bug fix?          | no
| Breaking change?  | no (breaks beta 28)
| New feature?      | no
| Deprecations?     | no
| Spec compliancy?  | yes
| Tests added/pass? | yes
| Fixed tickets     | https://github.com/babel/babylon/pull/761#issuecomment-336668141
| License           | MIT

Added some more tests for associativity, multiline parsing, and precedence.

Due to this operator being similar to `||`, and it being in the `LogicalORExpression` non-terminal in the grammar, should it move from `BinaryExpression` to the `LogicalExpression` AST node?

Update:

`??` has been moved to `LogicalExpression`

### CODE REVIEW

**Comment by hzoo** [comment]
Oh yeah that may be better actually

**Comment by azz** [comment]
Has been changed from `Binary`- to `LogicalExpression` in this PR.

**Comment by jridgewell** [comment]
So:

```js
a || b ?? c === (a || b) ?? c
a ?? b || c === (a ?? b) || c
```

But:
```js
a && b ?? c === (a && b) ?? c
a ?? b && c === a ?? (b && c)
```


Do we have any data for why this was chosen?

**Comment by littledan** [comment]
@jridgewell Is that what this code does? In the spec I wrote for `??`, it parses *exactly* like `||`, and in particular `&&` groups more tightly.

**Comment by jridgewell** [comment]
> Is that what this code does? 

Yes.

>  In the spec I wrote for ??, it parses exactly like ||, and in particular && groups more tightly.

That appears to be what's happening? I was just curious why it's not tighter than `&&` or looser than `||`.

**Comment by littledan** [comment]
@jridgewell I thought it would make sense to be exactly the same because people are likely to be upgrading their `||` to `??`, and why change anything? If I were to change it, it would be to be looser than `||`. Seems like this deserves a bug to discuss further.

**Comment by azz** [comment]
My intuition is it should be completely hot-swappable with `||`. Great for codemods/fixers.

**Comment by littledan** [comment]
Opened https://github.com/tc39-transfer/proposal-nullish-coalescing/issues/15 to discuss this question; for now, the spec is hot-swappable like that.

**Pull request merged**
