### PR TITLE
Arrow fns can't be used as the left side of a binary or ternary expression

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
| Q                 | A
| ----------------- | ---
| Bug fix?          | yes
| Breaking change?  | no
| New feature?      | no
| Deprecations?     | no
| Spec compliancy?  | yes
| Tests added/pass? | yes
| Fixed tickets     | #536 
| License           | MIT

I followed the same way used to forbid `() => {}()`: when parsing a binary/ternary expression, if an arrow function is encountered it is immediatly returned.

I didn't add the same check to `parseMaybeUnary` because this error is already caught when checking if the expression can be incremented/decremented. Should I add there the same check?

---

This is my first contribution to babel/babylon: do I have to sign a contributor license agreement?

### CODE REVIEW

**Comment by danez** [comment]
Will these examples still work?
```js
(() => {}) || true ;
(() => {}) ? a:b;
```

acorn fixed this with https://github.com/ternjs/acorn/commit/6a2de6dcfd4873a98614f36c5cc259b04af03b0a

**Comment by nicolo-ribaudo** [comment]
They will work because `potentialArrowAt` will be the start of the first parenthesis, so it will be different from the start of the arrow function.
Anyway, I won't have time to add the tests until the 13th.

**Comment by danez** [comment]
Ah nice. I add the two tests and merge it then. Thank you.

**Comment by nicolo-ribaudo** [comment]
Thank you for taking care of adding the two tests.

**Pull request merged**
